### ISSUE TITLE
Large Integer like Literals coming as float thereby loosing precision 

### ISSUE THREAD

**Issue by nmondal** [EsotericSoftware/yamlbeans#105]
https://gitlab.com/non.est.sacra/zoomba/issues/5

```yaml
invoice: 3484312312313131
date   : 2001-01-23
```
This, after parsing  (when guessNumberTypes is true)  is coming as float. It should come as string, ideally BigInteger. 
Fix is : when guessNumberTypes is true, we should we start parsing as BigDecimal.
Then, check if it is BigInt. Then downsize and see if we are loosing precision, if converting to String and parse back. We should not use float at all, only Double. 
Then, if we find that we can shrink it, we switch to String.

**Comment by NathanSweet** [comment]
`guessNumberTypes` is FUBAR, IMHO. The type should come from a class definition or else be String. I never want to get a number sometimes and a String other times, just because a String happened to look like a number.

A better solution is to parse to a value holder which you can then ask for a particular type, eg:
https://github.com/EsotericSoftware/jsonbeans/blob/master/src/com/esotericsoftware/jsonbeans/JsonValue.java#L210

Anyway, I'd merge a PR that improves `guessNumberTypes`. Likely it's sufficient to parse to long or double rather than BigDecimal, but whichever you'd like to do is fine since I don't use this feature (I don't actually use YAML anymore, as I found the format too wacky).

**Comment by Mr14huashao** [comment]
@NathanSweet 
This issue has been fixed, the PR #126  has been merged.
