### ISSUE TITLE
Unexpected handling of nulls

### ISSUE THREAD

**Issue by dwightguth** [EsotericSoftware/yamlbeans#109]
Because YAML 1.1 comes with a "null" value, I expected the translation of a null reference to be the YAML null value. However, it is not; it is instead the empty string, which makes it difficult to deserialize back into a null, since it is then impossible to distinguish between an empty java.lang.String and a null java.lang.String.

Fortunately for me, I am not using this library for deserialization and can simply adjust my deserialization code to correctly interpret the empty string in this case as a null value since an actual empty string is not valid in the position I use it in within the domain. However, I thought you should be informed because this should probably be seen as a bug and java nulls should probably become YAML nulls.

**Comment by NathanSweet** [comment]
If I serialized:
```ArrayList list = new ArrayList();
list.add("");
list.add(null);
```
I get:
```
- ""
-
```
I've since decided YAML is just too wacky to actually use in my projects (I generally use [JsonBeans](https://github.com/EsotericSoftware/jsonbeans/) or [Kryo](https://github.com/EsotericSoftware/kryo/)). I'm not sure what the right behavior here should be, `- null`? If you'd like to submit a PR to fix it, I'll merge.

**Comment by dwightguth** [comment]
I'm going to close this; turns out to have been my mistake, the empty string is apparently valid yaml syntax to represent the yaml null value. So it seems to already be what I expect semantically, it's just using a different syntax than I knew about previously.

**Comment by NathanSweet** [comment]
Things like this are why I don't use YAML anymore. :D
